version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - auto-hub-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=auto-hub-db
volumes:
  auto-hub-db:
